version: '3.8'

services:
  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # FastAPI service
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  # RQ Worker service
  rqworker:
    build: .
    container_name: rqworker
    command: rq worker processing --with-scheduler
    depends_on:
      - fastapi
      - redis
    environment:
      - REDIS_HOST=redis

volumes:
  redis-data:
