version: '3.8'

services:
  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # FastAPI service
  fastapi:
    build:
      context: ../
      dockerfile: collectionEndpoint/Dockerfile
    container_name: data-api
    ports:
      - "8000:8000"
    depends_on:
      - redis

    extra_hosts:
      host.docker.internal: host-gateway  # refrences host machine

volumes:
  redis-data:
